gradlift/src/gradlift/apps/website/account/urls.py
from django.conf.urls import url
from gradlift.apps.website.account import views

urlpatterns = [
    url(r'^$', views.AccountView.as_view(), name='account'),
    url(r'^general/$', views.AccountGeneralView.as_view(), name='account-general'),
    url(r'^password-reset/$', views.AccountPasswordChangeView.as_view(), name='account-password-reset'),
    url(r'^funds-received/$', views.AccountFundsReceivedView.as_view(), name='account-funds-received'),
    url(r'^backed-students/$', views.AccountBackedStudentsView.as_view(), name='account-backed-students'),
    url(r'^disable-account/$', views.DisableAccountView.as_view(), name='account-disable-account'),
]

gradlift/src/gradlift/apps/website/ajax/urls.py
from django.conf.urls import url
from gradlift.apps.website.ajax import views

urlpatterns = [
    url(r'^upload-profile-picture/$', views.UploadProfilePictureView.as_view(), name='upload-profile-picture'),
    url(r'^upload-cover-image/$', views.UploadCoverImageView.as_view(), name='upload-cover-image'),
    url(r'^upload-loan-document/$', views.UploadLoanDocumentView.as_view(), name='upload-loan-document'),
    url(r'^make-payment/$', views.MakePaymentView.as_view(), name='make-payment'),
    url(r'^pagination-update/$', views.PaginationUpdateView.as_view(), name='pagination-page-update')
]

gradlift/src/gradlift/apps/website/urls.py
from django.conf.urls import include, url

from django.views.decorators.cache import cache_page

from django.conf import settings
from django.conf.urls.static import static

from gradlift.apps.website import views
from gradlift.apps import Constants


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^find-students/$', views.DiscoverView.as_view(), name='discover'),
    url(r'^login/$',
        cache_page(Constants.CACHE_TIME_ONE_HOUR, key_prefix='login-page')(views.LoginView.as_view()),
        name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^register/$',
        cache_page(Constants.CACHE_TIME_ONE_HOUR, key_prefix='register-page')(views.RegisterView.as_view()),
        name='register'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(), name='password-reset'),
    url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', views.PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    url(r'^password-reset-email-sent/$', views.PasswordResetEmailSentView.as_view(), name='password-reset-email-sent'),
    url(r'^post-authenticated/$', views.PostAuthenticated.as_view(), name='post-authenticated'),
    url(r'^contact/$',
        cache_page(Constants.CACHE_TIME_ONE_HOUR, key_prefix='contact-page')(views.ContactView.as_view()),
        name='contact'),
    url(r'^terms-of-service/$',
        cache_page(Constants.CACHE_TIME_ONE_HOUR, key_prefix='terms-of-service-page')(views.TermsOfServiceView.as_view()),
        name='terms-of-service'),
    url(r'^privacy-policy/$',
        cache_page(Constants.CACHE_TIME_ONE_HOUR, key_prefix='privacy-policy-page')(views.PrivacyPolicyView.as_view()),
        name='privacy-policy'),
    url(r'^faq/$',
        cache_page(Constants.CACHE_TIME_ONE_HOUR, key_prefix='faq-page')(views.FAQView.as_view()),
        name='faq'),
    url(r'^blogs/$',
        cache_page(Constants.CACHE_TIME_ONE_HOUR, key_prefix='blogs-page')(views.BlogsView.as_view()),
        name='blogs'),
    url(r'^about-us/$',
        cache_page(Constants.CACHE_TIME_ONE_HOUR, key_prefix='about-us-page')(views.AboutUsView.as_view()),
        name='about-us'),
    url(r'^blog/(?P<blog_link>.+)/$',
        cache_page(Constants.CACHE_TIME_ONE_HOUR, key_prefix='blog-page')(views.BlogView.as_view()),
        name='blog'),
    url(r'^profile-completed/$', views.ProfileCompletedView.as_view(), name='profile-completed'),
    url(r'^profile/(?P<profile_link>.+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'^gradlift-scholarship/$', views.GradliftScholarshipView.as_view(), name='gradlift-scholarship'),
    url(r'^profile-edit/$', views.ProfileEditView.as_view(), name='profile-edit'),
    url(r'^activity-save/$', views.ActivitySaveView.as_view(), name='activity-save'),
    url(r'^activity-delete/$', views.CommentDeleteView.as_view(), name='activity-delete'),
    url(r'^agreed-to-terms/$', views.AgreedToTermsView.as_view(), name='agreed-to-terms'),
    url(r'^account/', include('gradlift.apps.website.account.urls')),
    url(r'^ajax/', include('gradlift.apps.website.ajax.urls')),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gradlift/src/gradlift/urls.py
from django.conf.urls import include, url
from django.contrib import admin


admin.autodiscover()

urlpatterns = [
    url(r'^', include('gradlift.apps.website.urls')),
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

gradlift/src/gradlift/apps/data/forms.py
from django import forms
from django.contrib.auth.models import User   # fill in custom user info then save it
from django.contrib.auth import forms as auth_forms
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from django.core.validators import validate_email

from gradlift.apps import Constants
from gradlift.apps.data import validators
from gradlift.apps.data import models
from gradlift.apps.data import tasks


class RegistrationForm(auth_forms.UserCreationForm):
    email = forms.EmailField(required=True, validators=[validators.validate_email])
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    referral_code = forms.CharField(required=False, validators=[validators.validate_referral_code])

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.username = self.cleaned_data['email']

        if commit:
            user.save()

        user_profile = models.UserProfile(user=user)

        try:
            referral_code = models.ReferralCode.objects.get(code=self.cleaned_data['referral_code'])
        except models.ReferralCode.DoesNotExist:
            referral_code = None

        user_profile.referral_code = referral_code

        if commit:
            user_profile.save()

        student = models.Student(user_profile=user_profile)

        if commit:
            student.save()

        student.send_welcome_email()

        return user

    def clean_password1(self):
        password = self.cleaned_data.get('password1')
        if len(password) < Constants.PASSWORD_MIN_LENGTH:
            raise validators.ValidationError(
                'This password is too short. It must contain at least %s characters.' % Constants.PASSWORD_MIN_LENGTH)
        return password


class LoginForm(auth_forms.AuthenticationForm):
    user = None

    error_messages = {
        'invalid_login': _("Please enter a correct email and password. "),
        'inactive': _("This account is inactive."),
    }

    def confirm_login_allowed(self, user):
        super(LoginForm, self).confirm_login_allowed(user=user)
        self.user = user

    def clean(self):
        try:
            username = self.cleaned_data.get('username')
            validate_email(username)
        except ValidationError:
            raise forms.ValidationError(
                self.error_messages['invalid_login'],
                code='invalid_login',
            )
        return super(LoginForm, self).clean()


class PasswordResetForm(auth_forms.PasswordResetForm):

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if not User.objects.filter(email=email).exists():
            raise validators.ValidationError(
                'There is no user associated with this email address.'
            )

        return email


class SetPasswordForm(auth_forms.SetPasswordForm):

    def clean_new_password1(self):
        new_password1 = self.cleaned_data.get('new_password1')
        if len(new_password1) < Constants.PASSWORD_MIN_LENGTH:
            raise validators.ValidationError(
                'This password is too short. It must contain at least %s characters.' % RegistrationForm.PASSWORD_MIN_LENGTH)
        return new_password1


class ActivityForm(forms.Form):

    message = forms.CharField(widget=forms.Textarea, max_length=5000, required=True)
    user_id = forms.CharField(widget=forms.HiddenInput())

    def save(self, request):
        user_profile = models.UserProfile.objects.get(user__pk=self.cleaned_data.get('user_id'))

        comment = models.Comment(
            comment=self.cleaned_data.get('message'),
            commentee=user_profile,
            commenter=request.user.profile)

        comment.save()

        if user_profile.notification_frequency == models.UserProfile.NOTIFICATION_CHOICE_INSTANTANEOUSLY:
            tasks.send_notification_email.delay(comment_id=comment.pk)


class CommentDeleteForm(forms.Form):

    comment_id = forms.IntegerField(required=True)
    commentee_user_id = forms.IntegerField(required=True)


class UserProfileForm(forms.Form):

    DEGREE_CHOICES = models.RefDegree.objects.get_options()
    DATE_MONTH_YEAR_FORMAT = [Constants.MONTH_YEAR_DATE_FORMAT]

    grad_story = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    overall_gpa = forms.CharField(max_length=10, required=False)
    hobbies = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)

    cover_image = forms.ImageField(required=False)
    profile_picture = forms.ImageField(required=False)

    is_high_school_student = forms.ChoiceField(widget=forms.RadioSelect, choices=(('1', 'Yes',), ('0', 'No',)))
    high_school_name = forms.CharField(required=False)
    high_school_graduation_date = forms.DateField(required=False, input_formats=DATE_MONTH_YEAR_FORMAT)
    high_school_projects = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    high_school_story = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)

    college_1_name = forms.CharField(required=False)
    college_1_start_date = forms.DateField(required=False, input_formats=DATE_MONTH_YEAR_FORMAT)
    college_1_end_date = forms.DateField(required=False, input_formats=DATE_MONTH_YEAR_FORMAT)
    college_1_degree = forms.ChoiceField(choices=DEGREE_CHOICES, required=False)
    college_1_major = forms.CharField(required=False)
    college_1_subjects = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    college_1_projects = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    college_1_story = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)

    attends_college_2 = forms.BooleanField(widget=forms.HiddenInput, required=False)
    college_2_name = forms.CharField(required=False)
    college_2_start_date = forms.DateField(required=False, input_formats=DATE_MONTH_YEAR_FORMAT)
    college_2_end_date = forms.DateField(required=False, input_formats=DATE_MONTH_YEAR_FORMAT)
    college_2_degree = forms.ChoiceField(choices=DEGREE_CHOICES, required=False)
    college_2_major = forms.CharField(required=False)
    college_2_subjects = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    college_2_projects = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    college_2_story = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)

    attends_college_3 = forms.BooleanField(widget=forms.HiddenInput, required=False)
    college_3_name = forms.CharField(required=False)
    college_3_start_date = forms.DateField(required=False, input_formats=DATE_MONTH_YEAR_FORMAT)
    college_3_end_date = forms.DateField(required=False, input_formats=DATE_MONTH_YEAR_FORMAT)
    college_3_degree = forms.ChoiceField(choices=DEGREE_CHOICES, required=False)
    college_3_major = forms.CharField(required=False)
    college_3_subjects = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    college_3_projects = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    college_3_story = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)

    attends_college_4 = forms.BooleanField(widget=forms.HiddenInput, required=False)
    college_4_name = forms.CharField(required=False)
    college_4_start_date = forms.DateField(required=False, input_formats=DATE_MONTH_YEAR_FORMAT)
    college_4_end_date = forms.DateField(required=False, input_formats=DATE_MONTH_YEAR_FORMAT)
    college_4_degree = forms.ChoiceField(choices=DEGREE_CHOICES, required=False)
    college_4_major = forms.CharField(required=False)
    college_4_subjects = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    college_4_projects = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    college_4_story = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)

    volunteer_projects_internships = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    more_about_me = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)

    def required_if_field_true(self, current_field, field):
        value = self.cleaned_data.get(current_field, '')
        if self.cleaned_data.get(field):
            if not value:
                raise forms.ValidationError("This field is required")
        return value

    def get_institution(self, name):
        if not name:
            return None
        try:
            institution = models.Institution.objects.get(name=name)
        except models.Institution.DoesNotExist:
            institution = None
        except models.Institution.MultipleObjectsReturned:
            institution = models.Institution.objects.filter(name=name).first()
        return institution

    def clean_high_school_name(self):
        high_school_name = self.required_if_field_true('high_school_name', 'is_high_school_student')
        return high_school_name, self.get_institution(name=high_school_name)

    def clean_high_school_graduation_date(self):
        return self.required_if_field_true("high_school_graduation_date", "is_high_school_student")

    def clean_college_1_name(self):
        college_name = self.cleaned_data.get('college_1_name', '')
        return college_name, self.get_institution(name=college_name)

    def clean_college_2_name(self):
        college_name = self.required_if_field_true("college_2_name", "attends_college_2")
        return college_name, self.get_institution(name=college_name)

    def clean_college_3_name(self):

gradlift/src/gradlift/apps/website/templates/profile/activity-feed.html
<div id="activity" style="padding-bottom: 0px">
    <h3 class="activity-header text-center" style="padding-top: 10px; margin-bottom: 10px;">Activity</h3>


    {% if user.is_authenticated %}
    <p class="text-center" style="margin-bottom: 10px;margin-top: 20px"><span style="text-transform: capitalize;"> {{ user.first_name }} </span>,
        Leave a comment below!</p>
    {% else %}
    <p style="margin-bottom: 10px;"><a href="{% url 'login' %}"> Login </a> to a leave a comment below!</p>
    {% endif %}


    <form method="POST" action="{% url 'activity-save' %}">

        {% csrf_token %}

        <textarea cols="10" id="id_message" maxlength="5000" placeholder="" name="message" rows="5"
                  style="height: 100px; margin-bottom: 0;"></textarea>

        <div class="um-field" style="padding-left: 0px; padding-right: 0px; padding-top: 0px">
            <div class="um-field-area">
                <button class="um-button btn-new" type="submit"
                        style="background: #3ba1da;height: 30px;padding-top: 6px !important;">
                    Submit
                </button>
            </div>
        </div>

        <input type="hidden" value="{{ user_id }}" name="user_id" id="id_user_id">
    </form>
    <br>

    <div style="max-height: 1000px; overflow-y: scroll; margin-top: 20px;">
        {% for comment in activities %}
        {% if comment.is_own_comment %}
        {% include 'profile/comment-self.html' %}
        {% else %}
        {% include 'profile/comment-others.html' %}
        {% endif %}
        {% endfor %}
    </div>

</div>

gradlift/src/gradlift/apps/website/templates/profile/comment-others.html
<div class="activity-feed-node activity-feed-node-right row">
    <div class="col-xs-12">
        <small class=" text-muted">
            <p class="title"> {{ comment.commenter }} </p>
        </small>
    </div>
    <hr class="hr-zero">
    <div class="col-xs-3 activity-avatar text-center pading-zero">
        <avatar>
            <a href="{% url 'profile' comment.profile_url %}">
                <img src="{{ comment.profile_picture }}"/>
            </a>
        </avatar>
        <br>
    </div>

        <div class="col-xs-12 time-right-margin">
        <div class="row" style="margin-right: 0px">
            <div class="col-xs-6">
                <small class="text-muted" style="padding-left: 15px">
                    <span class="glyphicon glyphicon-time"></span>April 07, 2016  11:37 pm
                </small>
            </div>
            <div class="col-xs-4">
                {% if comment.is_editable %}
        <form method="POST" action="{% url 'activity-delete' %}" class="comment-delete-form">
                        {% csrf_token %}
                        <input type="hidden" value="{{ comment.comment_id }}" name="comment_id">
                        <input type="hidden" value="{{ user_id }}" name="commentee_user_id">
                        <button type="submit" class="btn btn-danger pull-left waves-effect waves-effect" style="
                        float: right !important;
                        border: none;
                        color: #052E52;
                        background-color: #F7F7F7;
                        float: right !important;
                        margin-right: 15px;">
                            <span class="glyphicon glyphicon-trash" style="
                        color: #f75146;
                            ">
                            </span>
                        </button>
                    </form>
        {% endif %}
            </div>
        </div>
    </div>


</div>

gradlift/src/gradlift/apps/website/templates/profile/comment-self.html
<div class="activity-feed-node activity-feed-node-right row">
    <div class="col-xs-12">
        <small class=" text-muted">
            <p class="title"> {{ comment.commenter }} </p>
        </small>
    </div>
    <hr class="hr-zero">
    <div class="col-xs-8 pading-zero" >
        <box class="speech outer">
            <box class="speech inner">
                <div class="textwrapper">
                    {% if comment.amount %} <span class="amount"> {{ comment.amount }} $ </span> {% endif %}

                    <p class="message">
                        {{ comment.comment }}
                    </p>

                </div>
            </box>
        </box>
    </div>
    <div class="col-xs-3 activity-avatar text-center pading-zero">
        <avatar>
            <a href="{% url 'profile' comment.profile_url %}">
                <img src="{{ comment.profile_picture }}"/>
            </a>
        </avatar>
        <br>

    </div>
    <div class="col-xs-12 time-right-margin">
        <div class="row" style="margin-right: 0px">
            <div class="col-xs-6">
                <small class="text-muted" style="padding-left: 15px">
                    <span class="glyphicon glyphicon-time"></span>April 07, 2016  11:37 pm
                </small>
            </div>
            <div class="col-xs-4">
                {% if comment.is_editable %}
        <form method="POST" action="{% url 'activity-delete' %}" class="comment-delete-form">
                        {% csrf_token %}
                        <input type="hidden" value="{{ comment.comment_id }}" name="comment_id">
                        <input type="hidden" value="{{ user_id }}" name="commentee_user_id">
                        <button type="submit" class="btn btn-danger pull-left waves-effect waves-effect" style="
                        float: right !important;
                        border: none;
                        color: #052E52;
                        background-color: #F7F7F7;
                        float: right !important;
                        margin-right: 15px;">
                            <span class="glyphicon glyphicon-trash" style="
                        color: #f75146;
                            ">
                            </span>
                        </button>
                    </form>
        {% endif %}
            </div>
        </div>
    </div>
</div>

gradlift/src/gradlift/apps/website/templates/profile/payment-start.html
<div class="modal fade" id="payment-start-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document" style="margin-top: 100px;">
        <div class="modal-content">
            <form action="" method="POST" class="form-inline" id="payment-start-form">

                {% csrf_token %}

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Specify your contribution amount for <em id="supported-student-name"></em>
                    <br><br>
                        <div class="text-center">
                            All funds raised with GradLift go strait to the school and student loan providers
                        </div>
                    </h4>

                </div>
                <div class="modal-body">
                    <br>
                    <div class="lb_wrapper">
                        <div class="form">
                            <div class="btn-levels-container">

                                <div data-toggle="buttons" class="payment-options text-center">

                                    {% for payment_option in contribution_reference_data.payment_options %}
                                    <label class="btn btn-success btn-circle btn-lg">
                                        <input type="radio" name="selected-payment" id="selected-payment" value="{{payment_option}}">
                                        ${{payment_option}}
                                    </label>
                                    {% endfor %}

                                </div>
                            </div>
                            <br>
                        </div>
                    </div>
                    <br>

                    <div class="alert alert-danger" role="alert" id="invalid-amount-error" style="display: none">
                      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                      <span class="sr-only">Error:</span>
                      Select or enter a valid pledge amount
                    </div>
                    <div class="{% if IS_PAYMENT_RECURRING_ENABLED %} form-group {% else %} text-center {% endif %}">

                        <label class="sr-only" for="payment-amount">Amount (in dollars)</label>

                        <div class="input-group">
                            <div class="input-group-addon">Total $</div>
                            <input type="text" class="form-control" id="payment-amount" name="payment-amount" placeholder="Amount" required="true">
                            <div class="input-group-addon">.00</div>
                        </div>
                    </div>

                    {% if IS_PAYMENT_RECURRING_ENABLED %}

                        <div class="form-group">
                            <input
                                    name="is-recurring"
                                    id="is-recurring"
                                    type="checkbox"
                                    data-toggle="toggle"
                                    data-on="<i class='fa fa-play'></i> Recurring"
                                    data-off="<i class='fa fa-pause'></i> Not Recurring"
                                    data-onstyle="success"
                                    data-offstyle="info">
                        </div>

                        <div class="form-group">
                            <select id="contribution-type" name="contribution-type">
                                {% for contribution_type in contribution_reference_data.contribution_types %}
                                <option value="{{ contribution_type.code }}"> {{ contribution_type.name }} </option>
                                {% endfor %}
                            </select>
                        </div>

                    {% endif %}

                </div>
                <br>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary" style="width: 100%; padding-left: 0; padding-right: 0;" id="start-payment-processing">Next Step</button>
                </div>
            </form>
        </div>
    </div>
</div>

gradlift/src/gradlift/apps/website/templates/profile/profile-college.html
{% if college %}
<div class="um-col-1">

    {% if college.name %}
    <div class="um-field um-field-school" data-key="school">
        <div class="um-field-area">
            <div class="um-field-value">{{ college.name }}</div>
        </div>
    </div>
    {% endif %}

    {% if college.start_date %}
    <div class="um-field um-field-current_school_dates" data-key="current_school_dates">
        <div class="um-field-area">
            <div class="um-field-value">{{ college.start_date }} {% if college.graduation_date %} - {{ college.graduation_date }} {% endif %}</div>
        </div>
    </div>
    {% endif %}

    {% if college.degree %}
    <div class="um-field um-field-degreetype" data-key="degreetype">
        <div class="um-field-area">
            <div class="um-field-value">{{ college.degree }}</div>
        </div>
    </div>
    {% endif %}

    {% if college.major %}
    <div class="um-field um-field-major" data-key="major">
        <div class="um-field-area">
            <div class="um-field-value">{{ college.major }}</div>
        </div>
    </div>
    {% endif %}

    {% if college.subjects %}
    <div class="um-field um-field-mysubjects">
        <div class="um-field-label">
            <label>My Subjects</label>
            <div class="um-clear"></div>
        </div>
        <div class="um-field-area">
            <p class="um-field-value">{{ college.subjects }}</p>
        </div>
    </div>
    {% endif %}

    {% if college.projects %}
    <div class="um-field um-field-myprojects1" data-key="myprojects1">
        <div class="um-field-label">
            <label>My Projects</label>
            <div class="um-clear"></div>
        </div>
        <div class="um-field-area">
            <p class="um-field-value">{{ college.projects }}</p>
        </div>
    </div>
    {% endif %}

    {% if college.story %}
    <div class="um-field um-field-mystory" data-key="mystory">
        <div class="um-field-label">
            <label>My Story</label>
            <div class="um-clear"></div>
        </div>
        <div class="um-field-area">
            <p class="um-field-value">{{ college.story }}</p>
        </div>
    </div>
    {% endif %}
</div>
<br>
{% endif %}

gradlift/src/gradlift/apps/website/templates/profile/profile-high-school.html
{% if high_school %}

<div class="um-col-1">
    {% if high_school.name %}
    <div class="um-field um-field-school">
        <div class="um-field-area">
            <div class="um-field-value">{{ high_school.name }}</div>
        </div>
    </div>
    {% endif %}

    <div class="um-field um-field-major">
        <div class="um-field-area">
            <div class="um-field-value">{{ high_school.graduation_date }}</div>
        </div>
    </div>


    {% if high_school.projects %}
    <div class="um-field um-field-myprojects1_48" data-key="myprojects1_48">
        <div class="um-field-label">
            <label>My Projects</label>
        </div>
        <div class="um-field-area">
            <p class="um-field-value">{{ high_school.projects }}</p>
        </div>
    </div>
    {% endif %}


    {% if high_school.story %}
    <div class="um-field um-field-mystory_49" data-key="mystory_49">
        <div class="um-field-label">
            <label>My Story</label>
        </div>
        <div class="um-field-area">
            <p class="um-field-value">{{ high_school.story }}</p>
        </div>
    </div>
    {% endif %}

</div>
<br>
{% endif %}

gradlift/src/gradlift/apps/website/templates/profile/profile-image-upload.html
<div class="modal fade" id="{{ image_upload.modal_id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document" style="margin-top: 100px;">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">{{ image_upload.title }}</h4>
      </div>

      <div class="modal-body">
          <div class="croppie-container" data-file-input-name="{{ image_upload.name }}"></div>

          <div class="text-center">
            <form method="post" action="" enctype="multipart/form-data" class="file-drag-upload" data-upload-type="profile-image-upload">

                <div class="file-drop">
                    <div style="color: white; margin-bottom: 10px;">
                        {{ image_upload.title }}
                        </div>

                    <a>Browse</a>
                    <input type="file" name="document" multiple />
                </div>

            </form>
        </div>

      </div>

      <div class="modal-footer">
            <button type="button" class="btn btn-default image-upload-back-bottom">Back</button>
            <button type="button" class="btn btn-default image-upload-close-bottom" data-dismiss="modal">Close</button>
            <button
                class="upload-result btn btn-success"
                data-action-url="{{ image_upload.upload_url }}"
                data-onsuccess="{{ image_upload.onsuccess }}"
                data-onerror="{{ image_upload.onerror }}"
                data-file-input-name="{{ image_upload.name }}"
                data-file-input-id="{{ image_upload.id }}"
                data-dismiss="modal"
                    >
                Accept
            </button>
      </div>

    </div>
  </div>
</div>